### ISSUE TITLE
Data and scripts used for analysis? 

### ISSUE THREAD

**Issue by ghost** [svmiller/woi#1]
Howdy! 

I’m so glad I got the chance to read your working paper. It’s very good scholarship and I hope, to borrow parlance from Texas A&M, that you can PTHO it. (Publish the hell outta it)

I noticed this repository didn’t have the markup/latex used for generating the paper, and that most of the survey data and code used for simulations was not available? 

I don’t know the specifics of how private the survey data should be, but would it be at least possible to publish the code used for generating the simulations? 

Thanks and I hope things work out for this work. 😻

**Comment by svmiller** [comment]
Hello, after a year and a half. :P

The peer review process is mercifully coming to an end for this paper, so expect to see everything online very soon. Already raw source scripts and raw/polished data are online.
